name: model-training-evaluate
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: sondei/ium:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train and Evaluate model'
        shell: bash 
        run: |
          # Train and evaluate the model
          python3 prepareV2.py
          python3 train.py
          python3 evaluation.py
          
        