name: model-training-evaluate
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: sondei/ium:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install wget'
        run: |
          apt-get update
          apt-get install -y wget
      - name: 'Download training files'
        run: wget https://git.wmi.amu.edu.pl/s459312/ium_459312/src/branch/master/titles.csv https://git.wmi.amu.edu.pl/s459312/ium_459312/src/branch/master/prepareV2.py https://git.wmi.amu.edu.pl/s459312/ium_459312/src/branch/master/train.py https://git.wmi.amu.edu.pl/s459312/ium_459312/src/branch/master/evaluation.py
      - name: 'Train and Evaluate model'
        shell: bash 
        run: |
          # Train and evaluate the model
          docker run \
            --rm \
            -v ${PWD}:/app \
            -v ${PWD}/data:/app/data \
            sondei/ium:latest \
            python /app/prepareV2.py && \
            python /app/train.py && \
            python /app/evaluate.py && \
            cml-send-comment /app/metrics_file.txt